"""add user_id to audit_logs

Revision ID: 4490072962f8
Revises: 41f01391a046
Create Date: 2026-02-01 14:20:11.262433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4490072962f8'
down_revision: Union[str, Sequence[str], None] = '41f01391a046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['cnpj'])
    op.alter_column('user_company_role', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('user_company_role_user_id_fkey'), 'user_company_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_company_role', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_users_id_uuid'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_id_uuid'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_company_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_company_role_user_id_fkey'), 'user_company_role', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_company_role', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'user_id')
    op.drop_table('user_companies')
    # ### end Alembic commands ###
