"""create companies

Revision ID: 64d97f60f71a
Revises: 3ebb2e7ceab8
Create Date: 2026-01-29 03:27:16.066754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d97f60f71a'
down_revision: Union[str, Sequence[str], None] = '3ebb2e7ceab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('paid_at', sa.Date(), nullable=True))
    op.alter_column('guides', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.alter_column('guides', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('guides', 'paid_at')
    # ### end Alembic commands ###
