"""create tax rules table

Revision ID: 939ee63ca8fc
Revises: a813a7bb24fe
Create Date: 2026-01-28 08:09:54.045773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939ee63ca8fc'
down_revision: Union[str, Sequence[str], None] = 'a813a7bb24fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.String(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rules_id'), 'tax_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_rules_id'), table_name='tax_rules')
    op.drop_table('tax_rules')
    # ### end Alembic commands ###
