"""create apurations table

Revision ID: a813a7bb24fe
Revises: ec0d7fcd1204
Create Date: 2026-01-28 08:05:29.693450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a813a7bb24fe'
down_revision: Union[str, Sequence[str], None] = 'ec0d7fcd1204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('competence', sa.String(), nullable=False),
    sa.Column('total_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apurations_id'), 'apurations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apurations_id'), table_name='apurations')
    op.drop_table('apurations')
    # ### end Alembic commands ###
