"""companies table

Revision ID: ace67cbcc6db
Revises: 64d97f60f71a
Create Date: 2026-01-29 04:19:46.957380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace67cbcc6db'
down_revision: Union[str, Sequence[str], None] = '64d97f60f71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_cnpj_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.create_unique_constraint(op.f('companies_cnpj_key'), 'companies', ['cnpj'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
